# https://containers.dev/guide/dockerfile
version: '3.8'
services:
    devcontainer:
        build: .
        volumes:
            - ../..:/workspaces:cached
        network_mode: service:db
        command: sleep infinity

    db:
        image: postgres:latest
        restart: unless-stopped
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres

volumes:
    postgres-data:
